name: Deploy to Azure Functions

env:
  AZURE_WEBAPP_NAME: azure-function-app # set this to the name of your Azure Web App
  JAVA_VERSION: '17'                    # set this to the Java version to use
  DISTRIBUTION: zulu                    # set this to the Java distribution

on:
  create:
    tags:
      - '*' # Deploy on any tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for Dependabot

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: maven

      - name: Check Maven version
        run: mvn -version

      - name: Build with Maven
        run: mvn clean package

      - name: Create Zip File
        run: |
          cd ${{ github.workspace }}/target/azure-functions/${{ env.AZURE_WEBAPP_NAME }}
          zip -r ${{ github.workspace }}/${{ env.AZURE_WEBAPP_NAME }}.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: ${{ github.workspace }}/${{ env.AZURE_WEBAPP_NAME }}.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
