name: Deploy to Azure Functions

on:
  create:
    tags:
      - '*' # Deploy on any tag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for Dependabot

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          check-latest: true
          distribution: 'temurin'
          cache: maven

      - name: Check maven version
        run: mvn -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Azure Functions Action
        uses: Azure/functions-action@v1.5.1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
