name: Java CI with Maven

env:
  AZURE_WEBAPP_NAME: azure-function-app # set this to the name of your Azure Web App
  JAVA_VERSION: '17'                    # set this to the Java version to use
  DISTRIBUTION: zulu                    # set this to the Java distribution
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        cache: maven

    - name: Check Maven version
      run: mvn -version
          
    - name: Build with Maven
      run: mvn clean package
